# Generated by Django 5.0.1 on 2024-01-17 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stepsmodel',
            old_name='status',
            new_name='Status',
        ),
    ]
