# Generated by Django 5.0.1 on 2024-01-17 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0003_imgtitlestructuralwork_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imgtitlestructuralwork',
            name='user',
        ),
    ]
