# Generated by Django 5.0.1 on 2024-01-23 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0004_remove_imgtitlestructuralwork_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imgtitlestructuralwork',
            name='img',
            field=models.ImageField(upload_to='execution_work_images/'),
        ),
    ]
